export const products = [
  {
    id: 'ETH-USDT',
    base_currency: 'ETH',
    quote_currency: 'USDT',
    quote_increment: '0.01',
    base_increment: '0.00000001',
    display_name: 'ETH-USDT',
    min_market_funds: '1',
    margin_enabled: false,
    post_only: false,
    limit_only: false,
    cancel_only: false,
    status: 'online',
    status_message: '',
    trading_disabled: false,
    fx_stablecoin: false,
    max_slippage_percentage: '0.03000000',
    auction_mode: false,
    high_bid_limit_percentage: '',
  },
  {
    id: 'ETH-USD',
    base_currency: 'ETH',
    quote_currency: 'USD',
    quote_increment: '0.01',
    base_increment: '0.00000001',
    display_name: 'ETH-USD',
    min_market_funds: '1',
    margin_enabled: false,
    post_only: false,
    limit_only: false,
    cancel_only: false,
    status: 'online',
    status_message: '',
    trading_disabled: false,
    fx_stablecoin: false,
    max_slippage_percentage: '0.02000000',
    auction_mode: false,
    high_bid_limit_percentage: '',
  },
  {
    id: 'BTC-USD',
    base_currency: 'BTC',
    quote_currency: 'USD',
    quote_increment: '0.01',
    base_increment: '0.00000001',
    display_name: 'BTC-USD',
    min_market_funds: '1',
    margin_enabled: false,
    post_only: false,
    limit_only: false,
    cancel_only: false,
    status: 'online',
    status_message: '',
    trading_disabled: false,
    fx_stablecoin: false,
    max_slippage_percentage: '0.02000000',
    auction_mode: false,
    high_bid_limit_percentage: '',
  },
];

export const delistedProducts = [
  {
    id: 'ETH-USDC',
    base_currency: 'ETH',
    quote_currency: 'USDC',
    quote_increment: '1',
    base_increment: '0.00000001',
    display_name: 'ETH-USDC',
    min_market_funds: '1',
    margin_enabled: false,
    post_only: false,
    limit_only: false,
    cancel_only: false,
    status: 'delisted',
    status_message: '',
    trading_disabled: true,
    fx_stablecoin: false,
    max_slippage_percentage: '0.03000000',
    auction_mode: false,
    high_bid_limit_percentage: '',
  },
];
